<?php

namespace EmploiyerBundle\Repository;

/**
 * MessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessionRepository extends \Doctrine\ORM\EntityRepository
{
}
